# Server
server.port=${SERVER_PORT:8087}
spring.application.name=${APP_NAME:shipping-service}

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Pool
spring.datasource.hikari.maximum-pool-size=${DB_POOL_SIZE:10}
